version: '3.3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ThisIsACoolPassword12345"
    ports:
      - 1433:1433
    volumes:
      - mssql-storage:/var/opt/mssql
      
volumes:
  mssql-storage:
